const hotels = [
  {
    id: 1,
    name: 'Hotel A',
    image: require('../../assets/images/hotel1.png'),
    rating: 8.5,
    price: '1.500.000',
    description: 'This is a description of Hotel A.',
    amenities: ['Free WiFi', 'Swimming pool', 'Fitness center'],
    checkIn: '14:00',
    checkOut: '12:00',
  },
  {
    id: 2,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 3,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 4,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 5,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 6,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 7,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 8,
    name: 'Hotel B',
    image: require('../../assets/images/hotel2.png'),
    rating: 9.2,
    price: '2.000.000',
    description: 'This is a description of Hotel B.',
    amenities: ['Free WiFi', 'Restaurant', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
  },
  // Các khách sạn khác...
];

export default hotels;
